version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_database
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example